### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by Ronak1215** [malhotraarshdeepsingh/Employee-Management-System#1]
6:42:14 PM: error during build:
6:42:14 PM: Could not resolve "../utils/localStorage" from "src/context/AuthProvider.jsx"
6:42:14 PM: file: /opt/build/repo/src/context/AuthProvider.jsx
6:42:14 PM:     at getRollupError (file:///opt/build/repo/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
6:42:14 PM:     at error (file:///opt/build/repo/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
6:42:14 PM:     at ModuleLoader.handleInvalidResolvedId (file:///opt/build/repo/node_modules/rollup/dist/es/shared/node-entry.js:20088:24)
6:42:14 PM:     at file:///opt/build/repo/node_modules/rollup/dist/es/shared/node-entry.js:20048:26

getting this issue while deploying project

**Comment by malhotraarshdeepsingh** [comment]
This error is typically faced due to name case sensitivity in the file paths or the file not being not included in the deployment process. The project works perfectly fine locally, so it may be due to difference in environments.
Pls feel free to share additional details for further assistance, I appreciate your contribution for improving this project.
Best Regards
